GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "New blog 4",
    "author": "Tai Le",
    "url": "abc"
}

###
PUT http://localhost:3003/api/blogs/63eda05cfed003c41d3e338b
Content-Type: application/json

{
    "likes": 5,
}